# earlyoom is written in C, but the test suite is written in Go.
# The "go" build environment in Travis CI includes gcc, so just
# pretend we are a Go project.
language: go

addons:
  apt:
    packages:
    - pandoc

script:
  - cc --version
  - make
  - make test
  - make format
  - git diff
